source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MTLImage_Example' do
  pod 'MTLImage', :path => '../'
  pod 'MTLImage/MachineLearning', :path => '../'
  pod 'Fabric'
  pod 'Crashlytics'
end

target 'MTLImage_Tests' do
  pod 'MTLImage', :path => '../'
  pod 'Fabric'
  pod 'Crashlytics'
end
